[build-system]
requires = ["setuptools",
            "wheel",
            "versioneer-518",
            "numpy>=2.2.1",
            "Cython>=0.29"]

#build-backend = "setuptools.build_meta"

[setuptools]
version = "0.8.15"
