name: pypa twine pypi

on:
  push:
    tags:
      - v*

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.22.0

      - name: Build wheels
        env:
          CIBW_BEFORE_ALL: |
            sudo apt-get update && sudo apt-get install -y swig
            bash .github/workflows/prebuild.sh

          CIBW_BEFORE_BUILD: |
            pip install numpy
            python3 setup.py build_ext --inplace # Build the bindings

          CIBW_BUILD: |
            cp39-manylinux_x86_64
            cp310-manylinux_x86_64
            cp311-manylinux_x86_64
            cp312-manylinux_x86_64
            cp313-manylinux_x86_64

        run: cibuildwheel --platform linux --output-dir wheelhouse

      - name: Publish wheels to PyPI
        if: github.event_name == 'push'
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          pip install twine
          twine upload wheelhouse/*
