name: pypa twine pypi

on:
  push:
    tags:
      - v*

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.11.2

      - name: Build wheels
        env:
          CIBW_BEFORE_ALL: |
            sudo apt-get update && sudo apt-get install -y swig
            chmod +x .github/workflows/prebuild.sh && .github/workflows/prebuild.sh

          CIBW_BEFORE_BUILD: |
            pip install numpy

          CIBW_BUILD: cp311-manylinux_x86_64


        run: cibuildwheel --platform linux --output-dir wheelhouse

      - name: Publish wheels to PyPI
        if: github.event_name == 'push'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install twine
          twine upload wheelhouse/*


