name: Build Wheel Manylinux and upload to PyPi

on:
  push:
    tags: 
      - v*
  pull_request:
    tags:
      - v*
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CPPFLAGS: "-I/usr/include -I/usr/local/include -I/home/runner/stare/include"
      LDFLAGS: "-L/home/runner/stare/lib"
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}       
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: LS
      run: |
          ls -l
          python -c "import versioneer; print(versioneer.get_version())"
          pwd
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64
      with:
        python-versions: 'cp37-cp37m'
        pre-build-command: 'sh .github/workflows/prebuild.sh' # This script clones, builds, and installs STARE
        build-requirements: 'cython numpy'
    - name: LS
      run: |
        ls -l
        python -c "import versioneer; print(versioneer.get_version())"
    - name: Publish wheels to PyPI
      run: |
        twine upload  dist/*-manylinux*.whl
        # twine upload --repository testpypi dist/*-manylinux*.whl
    
