name: Build Wheel Manylinux and upload to PyPi

on:
  push:
    tags: 
      - v*
  pull_request:    
    tags:
      - v*
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      #CPPFLAGS: "-I/usr/include -I/usr/local/include -I/home/runner/stare/include/STARE/"
      #LDFLAGS: "-L/home/runner/stare/lib"
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}       
    steps:    
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      #if: ${{ github.event_name == 'pull_request' && inputs.debug_enabled }}
      if: ${{ failure() }}
      timeout-minutes: 15
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        pip install flake8 pytest numpy
        pip install twine   
        pip install setuptools swig wheel
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.7.1
      with:
        python-versions: 'cp312-cp312 cp313-cp313'
        pre-build-command: 'sh .github/workflows/prebuild.sh' # Clone, build, install STARE
        build-requirements: 'cython numpy'
    - name: Publish wheels to PyPI
      run: |
        twine upload  dist/*-manylinux*.whl
        #twine upload --repository testpypi dist/*-manylinux*.whl
    
