# This is a basic workflow to help you get started with Actions

name: pypi deployer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  Linux-build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: pull STARE
        uses: actions/checkout@master
        with:
          repository: SpatioTemporal/STARE
          path: STARE/
      - name: Install STARE
        shell: bash
        run: |
          cd STARE/
          set -x
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=~/stare ..
          make
          make install
          STARE_LIB_DIR=~/stare/lib/
          STARE_INCLUDE_DIR=~/stare/include/
      - name: build pystare
        run: | 
           python3 setup.py build_ext --inplace
      - name: build and upload manylinux wheels
        uses: Niraj-Kamdar/manylinux-wheel-builder@master
 
