name: Testrunnner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      #PWD_DIR: /home/runner
      CPPFLAGS: "-I/usr/include -I/usr/local/include -I/home/runner/stare/include"
      LDFLAGS: "-L/home/runner/stare/lib"
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }} 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: pull STARE
      uses: actions/checkout@master
      with:
          repository: SpatioTemporal/STARE
          path: STARE/
    - name: Install STARE
      shell: bash
      run: |
        cd STARE/
        set -x
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/stare ..
        make
        make install
        STARE_LIB_DIR=~/stare/lib/
        STARE_INCLUDE_DIR=~/stare/include/
    - name: build pystare
      run: | 
         python3 setup.py build_ext --inplace
         pip3 install .
    - name: Test with pytest
      run: |        
        pip install .[test]
        pytest
    - name: build and upload manylinux wheels
      uses: Niraj-Kamdar/manylinux-wheel-builder@master
    
